name: Обновление счётчика звёзд
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install Pillow requests
          
      - name: Генерация счётчика звёзд
        run: |
          python .github/scripts/generate_stars_counter.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Внесение изменения
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Ассеты/stars-counter.png
          git commit -m "Update stars counter" -a || echo "No changes to commit"
          git push